import React from 'react'

export const Notes = () => {
    return (
        <div className='space-y-12'>

            <ReQuirements />
            <TestRequirements />
            <Conditions />

        </div>
    )
}



const ReQuirements = () => {
    return (
        <div className='space-y-4'>
            <h1 className='text-[20px] font-weight-[600] leading-[24px] text-[#0B0A0B]'>
                Requirements
            </h1>

            <div className='space-y-4'>
                <Points point='Original International Passport or copy of data page if original is with the Canadian Immigration' />
                <Points point='Medical bio data form from the Embassy or upfront medical form to be generated by us.' />
                <Points point='Eyeglasses/contact lenses, hearing aids, specialist report, medications (If applicable)' />
                <Points point='Evidence of payment for all transactions' />
            </div>

        </div>
    )
}


const Conditions = () => {
    return (
        <div className='space-y-4'>
            <h1 className='text-[20px] font-weight-[600] leading-[24px] text-[#0B0A0B]'>
                Conditions
            </h1>

            <div className='space-y-4'>
                <Points point='Payments are to be made before appointments are confirmed.' />
                <Points point='All payments made are non-refundable.' />
                <Points point='If you will not be able to keep your appointment, kindly notify us via email (canadamedicals@qlifefamilyclinic.com) 5-working days prior to the date. You will be rescheduled based on availability of screening slots.' />
                <Points point='The screening takes 4 – 5 hours.' />
            </div>

        </div>
    )
}


const TestRequirements = () => {
    return (

        <div className='space-y-4'>
            <h1 className='text-[20px] font-weight-[600] leading-[24px] text-[#0B0A0B]'>
                Tests required
            </h1>
            <div className='space-y-4'>
                <TestPoints title='0 - 4' point='Detailed Medical History, Full Physical Examination' />
                <TestPoints title='5 - 10' point='Detailed Medical History, Full Physical Examination' />
                <TestPoints title='11 - 14' point='Detailed Medical History, Full Physical Examination, Chest X-Ray' />
                <TestPoints title='15 & above' point='Detailed Medical History, Full Physical Examination, Chest X-Ray, HIV, Syphilis, Serum Creatinine' />
            </div>
        </div>
    )
}


const Points = ({ point }: { point: string }) => {
    return (
        <div className='flex flex-row gap-5 items-center'>
            <div className='w-4 h-4 rounded-full flex items-center justify-center'>
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
                        <path d="M8.6 14.6L15.65 7.55L14.25 6.15L8.6 11.8L5.75 8.95L4.35 10.35L8.6 14.6ZM10 20C8.61667 20 7.31667 19.7375 6.1 19.2125C4.88333 18.6875 3.825 17.975 2.925 17.075C2.025 16.175 1.3125 15.1167 0.7875 13.9C0.2625 12.6833 0 11.3833 0 10C0 8.61667 0.2625 7.31667 0.7875 6.1C1.3125 4.88333 2.025 3.825 2.925 2.925C3.825 2.025 4.88333 1.3125 6.1 0.7875C7.31667 0.2625 8.61667 0 10 0C11.3833 0 12.6833 0.2625 13.9 0.7875C15.1167 1.3125 16.175 2.025 17.075 2.925C17.975 3.825 18.6875 4.88333 19.2125 6.1C19.7375 7.31667 20 8.61667 20 10C20 11.3833 19.7375 12.6833 19.2125 13.9C18.6875 15.1167 17.975 16.175 17.075 17.075C16.175 17.975 15.1167 18.6875 13.9 19.2125C12.6833 19.7375 11.3833 20 10 20ZM10 18C12.2333 18 14.125 17.225 15.675 15.675C17.225 14.125 18 12.2333 18 10C18 7.76667 17.225 5.875 15.675 4.325C14.125 2.775 12.2333 2 10 2C7.76667 2 5.875 2.775 4.325 4.325C2.775 5.875 2 7.76667 2 10C2 12.2333 2.775 14.125 4.325 15.675C5.875 17.225 7.76667 18 10 18Z" fill="#3FBA83" />
                    </svg>

                </div>

            </div>
            <div className='items-center justify-center max-w-[80%]'>
                <p className='text-sm font-weight-[400] leading-[16px] text-[#0B0A0B]'>
                    {point}
                </p>
            </div>
        </div>
    )
}

const TestPoints = ({ title, point }: { title: string, point: string }) => {
    return (
        <div className='grid grid-cols-12 gap-5 w-full'>
            <div className='col-span-2'>
                <h1 className='text-[16px] font-weight-[400] leading-[24px] text-[#707070]'>
                    {title}
                </h1>
            </div>
            <div className='col-span-10'>
                <p className='text-sm font-weight-[400] leading-[16px] text-[#0B0A0B]'>
                    {point}
                </p>
            </div>
        </div>
    )
}


